### ISSUE TITLE
AssetLib out of date

### ISSUE THREAD

**Issue by halotroop2288** [Aendryr/Godot-Date-Time-Input#1]
The version labeled "1.0.1" on AssetLib for Godot 4 is written in GDScript 3, not 4.
![image](https://github.com/Aendryr/Godot-Date-Time-Input/assets/30361266/412fe668-a656-41a3-b216-7f09be88eef1)

**Comment by Aendryr** [comment]
Hey @halotroop2288 thank you for telling me.
It seems I forgot to update the "Download Url"

I've just resubmitted it. Should be corrected soon.
